#----------------------------------------------
# cubosemantico.py
# cubosemantico
# Gerardo Chapa Quiroga 800249
# Tomas Castro Lopez 1033534
# Adolfo Castro Rojas 225591
# CREADO: 18/03/2013
# EDITADO: 19/03/2013
#----------------------------------------------

cubo_semantico = {
  	"Integer": {
			"Integer": {
				"+":"Integer", 
				"-":"Integer", 
				"*":"Integer", 
				"/":"Integer", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Integer",
				"==": "Boolean", 
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Float", 
				"-":"Float", 
				"*":"Float", 
				"/":"Float", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Integer", 
				"==": "Boolean",
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Double", 
				"-":"Double", 
				"*":"Double", 
				"/":"Double", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Integer", 
				"==": "Boolean",
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"List": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			}, 
		"Float":{
			"Integer": {
				"+":"Float", 
				"-":"Float", 
				"*":"Float", 
				"/":"Float", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Float",
				"==": "Boolean", 
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Float", 
				"-":"Float", 
				"*":"Float", 
				"/":"Float", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Float", 
				"==": "Boolean",
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Double", 
				"-":"Double", 
				"*":"Double", 
				"/":"Double", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Float",
				"==": "Boolean", 
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error",
				"==": "Error", 
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error",
				"==": "Error", 
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"List": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			}, 
		"Double":{
			"Integer": {
				"+":"Double", 
				"-":"Double", 
				"*":"Double", 
				"/":"Double", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Double", 
				"==": "Boolean",
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Double", 
				"-":"Double", 
				"*":"Double", 
				"/":"Double", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Double", 
				"==": "Boolean",
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Double", 
				"-":"Double", 
				"*":"Double", 
				"/":"Double", 
				">":"Boolean", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Boolean", 
				"=":"Double",
				"==": "Boolean", 
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"List": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			}, 
		"String":{
			"Integer": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"String", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"String", 
				"==": "Boolean",
				"!=":"Boolean",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"List": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			}, 
		"Boolean":{
			"Integer": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Boolean", 
				"==":"Boolean",
				"!=":"Boolean",
				"and":"Boolean", 
				"or":"Boolean",
				},
			"List": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			},
		"List":{
			"Integer": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Boolean",
				"<=":"Boolean",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"List": {
				"+":"List", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error",
				">=":"Error",
				"<=":"Error", 
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			},
		"Array":{
			"Integer": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Float": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Double": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"String": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				}, 
			"Boolean": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==":"Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"List": {
				"+":"Error", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			"Array": {
				"+":"Array", 
				"-":"Error", 
				"*":"Error", 
				"/":"Error", 
				">":"Error", 
				">=":"Error",
				"<=":"Error",
				"<":"Error", 
				"=":"Error", 
				"==": "Error",
				"!=":"Error",
				"and":"Error", 
				"or":"Error",
				},
			},
		}
